stages:
  - build

docker-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_DOCKER_HUB_USER" -p "$CI_DOCKER_HUB_PASSWORD" docker.io
  script:
    - docker build -t carlonluca/darkmediawiki:"$VERSION" -t carlonluca/darkmediawiki:latest .
    - docker push carlonluca/darkmediawiki:"$VERSION"
    - docker push carlonluca/darkmediawiki:latest
  rules:
    - when: manual
